version: "3"
services:
  app:
    command: ["go", "run", "main.go"]
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: app
    tty: true
    volumes:
      - ./server:/go/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    command: ["npm", "start"]
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    stdin_open: true
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    platform: linux/x86_64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sysimpl_bravo_db
      MYSQL_USER: sysimpl
      MYSQL_PASSWORD: sysimpl
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql  # uncomment to keep the data
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
    - "8001:80"
    depends_on:
      - db
