FROM node:18.12.0

WORKDIR /frontend

#RUN npm install
#RUN npm install dayjs
#RUN npm install @fullcalendar/react @fullcalendar/daygrid @fullcalendar/timegrid @fullcalendar/interaction @fullcalendar/core @mui/x-date-pickers/